// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Item struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID"`
	Title                string   `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title"`
	Description          string   `protobuf:"bytes,3,opt,name=Description,proto3" json:"Description"`
	UserID               int32    `protobuf:"varint,4,opt,name=UserID,proto3" json:"UserID"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Item) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Item) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Item) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type UserCredidentials struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserCredidentials) Reset()         { *m = UserCredidentials{} }
func (m *UserCredidentials) String() string { return proto.CompactTextString(m) }
func (*UserCredidentials) ProtoMessage()    {}
func (*UserCredidentials) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *UserCredidentials) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCredidentials.Unmarshal(m, b)
}
func (m *UserCredidentials) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCredidentials.Marshal(b, m, deterministic)
}
func (m *UserCredidentials) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCredidentials.Merge(m, src)
}
func (m *UserCredidentials) XXX_Size() int {
	return xxx_messageInfo_UserCredidentials.Size(m)
}
func (m *UserCredidentials) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCredidentials.DiscardUnknown(m)
}

var xxx_messageInfo_UserCredidentials proto.InternalMessageInfo

func (m *UserCredidentials) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserCredidentials) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type User struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID"`
	Username             string   `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username"`
	FullName             string   `protobuf:"bytes,3,opt,name=FullName,proto3" json:"FullName"`
	Password             string   `protobuf:"bytes,4,opt,name=Password,proto3" json:"Password"`
	Items                []*Item  `protobuf:"bytes,5,rep,name=Items,proto3" json:"Items"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetItems() []*Item {
	if m != nil {
		return m.Items
	}
	return nil
}

type CreateItemReq struct {
	Item                 *Item    `protobuf:"bytes,1,opt,name=Item,proto3" json:"Item"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateItemReq) Reset()         { *m = CreateItemReq{} }
func (m *CreateItemReq) String() string { return proto.CompactTextString(m) }
func (*CreateItemReq) ProtoMessage()    {}
func (*CreateItemReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *CreateItemReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateItemReq.Unmarshal(m, b)
}
func (m *CreateItemReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateItemReq.Marshal(b, m, deterministic)
}
func (m *CreateItemReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateItemReq.Merge(m, src)
}
func (m *CreateItemReq) XXX_Size() int {
	return xxx_messageInfo_CreateItemReq.Size(m)
}
func (m *CreateItemReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateItemReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateItemReq proto.InternalMessageInfo

func (m *CreateItemReq) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type CreateItemRes struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message"`
	ID                   int32    `protobuf:"varint,2,opt,name=ID,proto3" json:"ID"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateItemRes) Reset()         { *m = CreateItemRes{} }
func (m *CreateItemRes) String() string { return proto.CompactTextString(m) }
func (*CreateItemRes) ProtoMessage()    {}
func (*CreateItemRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *CreateItemRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateItemRes.Unmarshal(m, b)
}
func (m *CreateItemRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateItemRes.Marshal(b, m, deterministic)
}
func (m *CreateItemRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateItemRes.Merge(m, src)
}
func (m *CreateItemRes) XXX_Size() int {
	return xxx_messageInfo_CreateItemRes.Size(m)
}
func (m *CreateItemRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateItemRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateItemRes proto.InternalMessageInfo

func (m *CreateItemRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CreateItemRes) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

type GetItemReq struct {
	UserID               int32    `protobuf:"varint,1,opt,name=UserID,proto3" json:"UserID"`
	ID                   int32    `protobuf:"varint,2,opt,name=ID,proto3" json:"ID"`
	Title                string   `protobuf:"bytes,3,opt,name=Title,proto3" json:"Title"`
	Description          string   `protobuf:"bytes,4,opt,name=Description,proto3" json:"Description"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetItemReq) Reset()         { *m = GetItemReq{} }
func (m *GetItemReq) String() string { return proto.CompactTextString(m) }
func (*GetItemReq) ProtoMessage()    {}
func (*GetItemReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *GetItemReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetItemReq.Unmarshal(m, b)
}
func (m *GetItemReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetItemReq.Marshal(b, m, deterministic)
}
func (m *GetItemReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetItemReq.Merge(m, src)
}
func (m *GetItemReq) XXX_Size() int {
	return xxx_messageInfo_GetItemReq.Size(m)
}
func (m *GetItemReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetItemReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetItemReq proto.InternalMessageInfo

func (m *GetItemReq) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *GetItemReq) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *GetItemReq) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *GetItemReq) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type GetItemRes struct {
	Item                 []*Item  `protobuf:"bytes,1,rep,name=Item,proto3" json:"Item"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetItemRes) Reset()         { *m = GetItemRes{} }
func (m *GetItemRes) String() string { return proto.CompactTextString(m) }
func (*GetItemRes) ProtoMessage()    {}
func (*GetItemRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *GetItemRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetItemRes.Unmarshal(m, b)
}
func (m *GetItemRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetItemRes.Marshal(b, m, deterministic)
}
func (m *GetItemRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetItemRes.Merge(m, src)
}
func (m *GetItemRes) XXX_Size() int {
	return xxx_messageInfo_GetItemRes.Size(m)
}
func (m *GetItemRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetItemRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetItemRes proto.InternalMessageInfo

func (m *GetItemRes) GetItem() []*Item {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *GetItemRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type UpdateItemReq struct {
	Item                 *Item    `protobuf:"bytes,1,opt,name=Item,proto3" json:"Item"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateItemReq) Reset()         { *m = UpdateItemReq{} }
func (m *UpdateItemReq) String() string { return proto.CompactTextString(m) }
func (*UpdateItemReq) ProtoMessage()    {}
func (*UpdateItemReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{7}
}

func (m *UpdateItemReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateItemReq.Unmarshal(m, b)
}
func (m *UpdateItemReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateItemReq.Marshal(b, m, deterministic)
}
func (m *UpdateItemReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateItemReq.Merge(m, src)
}
func (m *UpdateItemReq) XXX_Size() int {
	return xxx_messageInfo_UpdateItemReq.Size(m)
}
func (m *UpdateItemReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateItemReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateItemReq proto.InternalMessageInfo

func (m *UpdateItemReq) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type UpdateItemRes struct {
	Item                 *Item    `protobuf:"bytes,1,opt,name=Item,proto3" json:"Item"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateItemRes) Reset()         { *m = UpdateItemRes{} }
func (m *UpdateItemRes) String() string { return proto.CompactTextString(m) }
func (*UpdateItemRes) ProtoMessage()    {}
func (*UpdateItemRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{8}
}

func (m *UpdateItemRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateItemRes.Unmarshal(m, b)
}
func (m *UpdateItemRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateItemRes.Marshal(b, m, deterministic)
}
func (m *UpdateItemRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateItemRes.Merge(m, src)
}
func (m *UpdateItemRes) XXX_Size() int {
	return xxx_messageInfo_UpdateItemRes.Size(m)
}
func (m *UpdateItemRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateItemRes.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateItemRes proto.InternalMessageInfo

func (m *UpdateItemRes) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *UpdateItemRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type DeleteItemReq struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteItemReq) Reset()         { *m = DeleteItemReq{} }
func (m *DeleteItemReq) String() string { return proto.CompactTextString(m) }
func (*DeleteItemReq) ProtoMessage()    {}
func (*DeleteItemReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{9}
}

func (m *DeleteItemReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteItemReq.Unmarshal(m, b)
}
func (m *DeleteItemReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteItemReq.Marshal(b, m, deterministic)
}
func (m *DeleteItemReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteItemReq.Merge(m, src)
}
func (m *DeleteItemReq) XXX_Size() int {
	return xxx_messageInfo_DeleteItemReq.Size(m)
}
func (m *DeleteItemReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteItemReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteItemReq proto.InternalMessageInfo

func (m *DeleteItemReq) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

type DeleteItemRes struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteItemRes) Reset()         { *m = DeleteItemRes{} }
func (m *DeleteItemRes) String() string { return proto.CompactTextString(m) }
func (*DeleteItemRes) ProtoMessage()    {}
func (*DeleteItemRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{10}
}

func (m *DeleteItemRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteItemRes.Unmarshal(m, b)
}
func (m *DeleteItemRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteItemRes.Marshal(b, m, deterministic)
}
func (m *DeleteItemRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteItemRes.Merge(m, src)
}
func (m *DeleteItemRes) XXX_Size() int {
	return xxx_messageInfo_DeleteItemRes.Size(m)
}
func (m *DeleteItemRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteItemRes.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteItemRes proto.InternalMessageInfo

func (m *DeleteItemRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type CreateUserReq struct {
	User                 *User    `protobuf:"bytes,1,opt,name=User,proto3" json:"User"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserReq) Reset()         { *m = CreateUserReq{} }
func (m *CreateUserReq) String() string { return proto.CompactTextString(m) }
func (*CreateUserReq) ProtoMessage()    {}
func (*CreateUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{11}
}

func (m *CreateUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserReq.Unmarshal(m, b)
}
func (m *CreateUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserReq.Marshal(b, m, deterministic)
}
func (m *CreateUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserReq.Merge(m, src)
}
func (m *CreateUserReq) XXX_Size() int {
	return xxx_messageInfo_CreateUserReq.Size(m)
}
func (m *CreateUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserReq proto.InternalMessageInfo

func (m *CreateUserReq) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type CreateUserRes struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message"`
	UserID               int32    `protobuf:"varint,2,opt,name=UserID,proto3" json:"UserID"`
	Token                string   `protobuf:"bytes,3,opt,name=Token,proto3" json:"Token"`
	RefreshToken         string   `protobuf:"bytes,4,opt,name=RefreshToken,proto3" json:"RefreshToken"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRes) Reset()         { *m = CreateUserRes{} }
func (m *CreateUserRes) String() string { return proto.CompactTextString(m) }
func (*CreateUserRes) ProtoMessage()    {}
func (*CreateUserRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{12}
}

func (m *CreateUserRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRes.Unmarshal(m, b)
}
func (m *CreateUserRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRes.Marshal(b, m, deterministic)
}
func (m *CreateUserRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRes.Merge(m, src)
}
func (m *CreateUserRes) XXX_Size() int {
	return xxx_messageInfo_CreateUserRes.Size(m)
}
func (m *CreateUserRes) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRes.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRes proto.InternalMessageInfo

func (m *CreateUserRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *CreateUserRes) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *CreateUserRes) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *CreateUserRes) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type GetUserReq struct {
	User                 *User    `protobuf:"bytes,1,opt,name=User,proto3" json:"User"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserReq) Reset()         { *m = GetUserReq{} }
func (m *GetUserReq) String() string { return proto.CompactTextString(m) }
func (*GetUserReq) ProtoMessage()    {}
func (*GetUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{13}
}

func (m *GetUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserReq.Unmarshal(m, b)
}
func (m *GetUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserReq.Marshal(b, m, deterministic)
}
func (m *GetUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserReq.Merge(m, src)
}
func (m *GetUserReq) XXX_Size() int {
	return xxx_messageInfo_GetUserReq.Size(m)
}
func (m *GetUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserReq proto.InternalMessageInfo

func (m *GetUserReq) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type GetUserRes struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=Users,proto3" json:"Users"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRes) Reset()         { *m = GetUserRes{} }
func (m *GetUserRes) String() string { return proto.CompactTextString(m) }
func (*GetUserRes) ProtoMessage()    {}
func (*GetUserRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{14}
}

func (m *GetUserRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRes.Unmarshal(m, b)
}
func (m *GetUserRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRes.Marshal(b, m, deterministic)
}
func (m *GetUserRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRes.Merge(m, src)
}
func (m *GetUserRes) XXX_Size() int {
	return xxx_messageInfo_GetUserRes.Size(m)
}
func (m *GetUserRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRes proto.InternalMessageInfo

func (m *GetUserRes) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *GetUserRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type UpdateUserReq struct {
	User                 *User    `protobuf:"bytes,1,opt,name=User,proto3" json:"User"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserReq) Reset()         { *m = UpdateUserReq{} }
func (m *UpdateUserReq) String() string { return proto.CompactTextString(m) }
func (*UpdateUserReq) ProtoMessage()    {}
func (*UpdateUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{15}
}

func (m *UpdateUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserReq.Unmarshal(m, b)
}
func (m *UpdateUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserReq.Marshal(b, m, deterministic)
}
func (m *UpdateUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserReq.Merge(m, src)
}
func (m *UpdateUserReq) XXX_Size() int {
	return xxx_messageInfo_UpdateUserReq.Size(m)
}
func (m *UpdateUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserReq proto.InternalMessageInfo

func (m *UpdateUserReq) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserRes struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRes) Reset()         { *m = UpdateUserRes{} }
func (m *UpdateUserRes) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRes) ProtoMessage()    {}
func (*UpdateUserRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{16}
}

func (m *UpdateUserRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRes.Unmarshal(m, b)
}
func (m *UpdateUserRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRes.Marshal(b, m, deterministic)
}
func (m *UpdateUserRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRes.Merge(m, src)
}
func (m *UpdateUserRes) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRes.Size(m)
}
func (m *UpdateUserRes) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRes.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRes proto.InternalMessageInfo

func (m *UpdateUserRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type DeleteUserReq struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserReq) Reset()         { *m = DeleteUserReq{} }
func (m *DeleteUserReq) String() string { return proto.CompactTextString(m) }
func (*DeleteUserReq) ProtoMessage()    {}
func (*DeleteUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{17}
}

func (m *DeleteUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserReq.Unmarshal(m, b)
}
func (m *DeleteUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserReq.Marshal(b, m, deterministic)
}
func (m *DeleteUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserReq.Merge(m, src)
}
func (m *DeleteUserReq) XXX_Size() int {
	return xxx_messageInfo_DeleteUserReq.Size(m)
}
func (m *DeleteUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserReq proto.InternalMessageInfo

func (m *DeleteUserReq) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

type DeleteUserRes struct {
	Message              string   `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRes) Reset()         { *m = DeleteUserRes{} }
func (m *DeleteUserRes) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRes) ProtoMessage()    {}
func (*DeleteUserRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{18}
}

func (m *DeleteUserRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRes.Unmarshal(m, b)
}
func (m *DeleteUserRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRes.Marshal(b, m, deterministic)
}
func (m *DeleteUserRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRes.Merge(m, src)
}
func (m *DeleteUserRes) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRes.Size(m)
}
func (m *DeleteUserRes) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRes.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRes proto.InternalMessageInfo

func (m *DeleteUserRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type LoginUserReq struct {
	UserCredidentials    *UserCredidentials `protobuf:"bytes,1,opt,name=UserCredidentials,proto3" json:"UserCredidentials"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *LoginUserReq) Reset()         { *m = LoginUserReq{} }
func (m *LoginUserReq) String() string { return proto.CompactTextString(m) }
func (*LoginUserReq) ProtoMessage()    {}
func (*LoginUserReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{19}
}

func (m *LoginUserReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginUserReq.Unmarshal(m, b)
}
func (m *LoginUserReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginUserReq.Marshal(b, m, deterministic)
}
func (m *LoginUserReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginUserReq.Merge(m, src)
}
func (m *LoginUserReq) XXX_Size() int {
	return xxx_messageInfo_LoginUserReq.Size(m)
}
func (m *LoginUserReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginUserReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginUserReq proto.InternalMessageInfo

func (m *LoginUserReq) GetUserCredidentials() *UserCredidentials {
	if m != nil {
		return m.UserCredidentials
	}
	return nil
}

type LoginUserRes struct {
	Token                string   `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=RefreshToken,proto3" json:"RefreshToken"`
	UserID               int32    `protobuf:"varint,3,opt,name=UserID,proto3" json:"UserID"`
	Message              string   `protobuf:"bytes,4,opt,name=Message,proto3" json:"Message"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginUserRes) Reset()         { *m = LoginUserRes{} }
func (m *LoginUserRes) String() string { return proto.CompactTextString(m) }
func (*LoginUserRes) ProtoMessage()    {}
func (*LoginUserRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{20}
}

func (m *LoginUserRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginUserRes.Unmarshal(m, b)
}
func (m *LoginUserRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginUserRes.Marshal(b, m, deterministic)
}
func (m *LoginUserRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginUserRes.Merge(m, src)
}
func (m *LoginUserRes) XXX_Size() int {
	return xxx_messageInfo_LoginUserRes.Size(m)
}
func (m *LoginUserRes) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginUserRes.DiscardUnknown(m)
}

var xxx_messageInfo_LoginUserRes proto.InternalMessageInfo

func (m *LoginUserRes) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginUserRes) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *LoginUserRes) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *LoginUserRes) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type RefreshTokenReq struct {
	RefreshToken         string   `protobuf:"bytes,2,opt,name=RefreshToken,proto3" json:"RefreshToken"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshTokenReq) Reset()         { *m = RefreshTokenReq{} }
func (m *RefreshTokenReq) String() string { return proto.CompactTextString(m) }
func (*RefreshTokenReq) ProtoMessage()    {}
func (*RefreshTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{21}
}

func (m *RefreshTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshTokenReq.Unmarshal(m, b)
}
func (m *RefreshTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshTokenReq.Marshal(b, m, deterministic)
}
func (m *RefreshTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshTokenReq.Merge(m, src)
}
func (m *RefreshTokenReq) XXX_Size() int {
	return xxx_messageInfo_RefreshTokenReq.Size(m)
}
func (m *RefreshTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshTokenReq proto.InternalMessageInfo

func (m *RefreshTokenReq) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

type RefreshTokenRes struct {
	Token                string   `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token"`
	RefreshToken         string   `protobuf:"bytes,2,opt,name=RefreshToken,proto3" json:"RefreshToken"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshTokenRes) Reset()         { *m = RefreshTokenRes{} }
func (m *RefreshTokenRes) String() string { return proto.CompactTextString(m) }
func (*RefreshTokenRes) ProtoMessage()    {}
func (*RefreshTokenRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{22}
}

func (m *RefreshTokenRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshTokenRes.Unmarshal(m, b)
}
func (m *RefreshTokenRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshTokenRes.Marshal(b, m, deterministic)
}
func (m *RefreshTokenRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshTokenRes.Merge(m, src)
}
func (m *RefreshTokenRes) XXX_Size() int {
	return xxx_messageInfo_RefreshTokenRes.Size(m)
}
func (m *RefreshTokenRes) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshTokenRes.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshTokenRes proto.InternalMessageInfo

func (m *RefreshTokenRes) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *RefreshTokenRes) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func init() {
	proto.RegisterType((*Item)(nil), "proto.Item")
	proto.RegisterType((*UserCredidentials)(nil), "proto.UserCredidentials")
	proto.RegisterType((*User)(nil), "proto.User")
	proto.RegisterType((*CreateItemReq)(nil), "proto.CreateItemReq")
	proto.RegisterType((*CreateItemRes)(nil), "proto.CreateItemRes")
	proto.RegisterType((*GetItemReq)(nil), "proto.GetItemReq")
	proto.RegisterType((*GetItemRes)(nil), "proto.GetItemRes")
	proto.RegisterType((*UpdateItemReq)(nil), "proto.UpdateItemReq")
	proto.RegisterType((*UpdateItemRes)(nil), "proto.UpdateItemRes")
	proto.RegisterType((*DeleteItemReq)(nil), "proto.DeleteItemReq")
	proto.RegisterType((*DeleteItemRes)(nil), "proto.DeleteItemRes")
	proto.RegisterType((*CreateUserReq)(nil), "proto.CreateUserReq")
	proto.RegisterType((*CreateUserRes)(nil), "proto.CreateUserRes")
	proto.RegisterType((*GetUserReq)(nil), "proto.GetUserReq")
	proto.RegisterType((*GetUserRes)(nil), "proto.GetUserRes")
	proto.RegisterType((*UpdateUserReq)(nil), "proto.UpdateUserReq")
	proto.RegisterType((*UpdateUserRes)(nil), "proto.UpdateUserRes")
	proto.RegisterType((*DeleteUserReq)(nil), "proto.DeleteUserReq")
	proto.RegisterType((*DeleteUserRes)(nil), "proto.DeleteUserRes")
	proto.RegisterType((*LoginUserReq)(nil), "proto.LoginUserReq")
	proto.RegisterType((*LoginUserRes)(nil), "proto.LoginUserRes")
	proto.RegisterType((*RefreshTokenReq)(nil), "proto.RefreshTokenReq")
	proto.RegisterType((*RefreshTokenRes)(nil), "proto.RefreshTokenRes")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 621 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xcf, 0x6e, 0xd3, 0x4e,
	0x10, 0x96, 0x1d, 0xbb, 0xfd, 0x75, 0xd2, 0xfe, 0x50, 0x97, 0x0a, 0x59, 0xbe, 0x34, 0xec, 0x29,
	0x3d, 0x50, 0xa0, 0x08, 0x09, 0x2e, 0x5c, 0x1a, 0xb5, 0x0a, 0x05, 0x84, 0x0c, 0xe5, 0x1e, 0x9a,
	0x6d, 0xb1, 0x70, 0xed, 0xe0, 0x71, 0x41, 0x82, 0x67, 0xe0, 0x95, 0x78, 0x36, 0xb4, 0xeb, 0xb5,
	0x77, 0xc7, 0x5e, 0xdc, 0x20, 0x4e, 0xf5, 0x7c, 0xb3, 0xf3, 0xef, 0xfb, 0x26, 0x53, 0x80, 0x1b,
	0x14, 0xe5, 0xe1, 0xaa, 0x2c, 0xaa, 0x82, 0x85, 0xea, 0x0f, 0xbf, 0x84, 0x60, 0x5e, 0x89, 0x6b,
	0xf6, 0x3f, 0xf8, 0xf3, 0x59, 0xe4, 0x4d, 0xbc, 0x69, 0x98, 0xf8, 0xf3, 0x19, 0xdb, 0x83, 0xf0,
	0x7d, 0x5a, 0x65, 0x22, 0xf2, 0x27, 0xde, 0x74, 0x2b, 0xa9, 0x0d, 0x36, 0x81, 0xf1, 0x4c, 0xe0,
	0x45, 0x99, 0xae, 0xaa, 0xb4, 0xc8, 0xa3, 0x91, 0xf2, 0xd9, 0x10, 0xbb, 0x07, 0x1b, 0xe7, 0x28,
	0xca, 0xf9, 0x2c, 0x0a, 0x54, 0x2e, 0x6d, 0xf1, 0x33, 0xd8, 0x95, 0x5f, 0xc7, 0xa5, 0x58, 0xa6,
	0x4b, 0x91, 0x57, 0xe9, 0x22, 0x43, 0x16, 0xc3, 0x7f, 0x12, 0xcc, 0x17, 0xd7, 0x42, 0x95, 0xde,
	0x4a, 0x5a, 0x5b, 0xfa, 0xde, 0x2e, 0x10, 0xbf, 0x15, 0xe5, 0x52, 0xf7, 0xd0, 0xda, 0xfc, 0xa7,
	0x07, 0x81, 0x7c, 0xd8, 0xeb, 0xda, 0x4e, 0xe8, 0xf7, 0x13, 0x9e, 0xdc, 0x64, 0xd9, 0x1b, 0xe9,
	0xab, 0x1b, 0x6f, 0x6d, 0x52, 0x2c, 0xa0, 0xc5, 0xd8, 0x7d, 0x08, 0x25, 0x43, 0x18, 0x85, 0x93,
	0xd1, 0x74, 0x7c, 0x34, 0xae, 0xf9, 0x3b, 0x94, 0x58, 0x52, 0x7b, 0xf8, 0x23, 0xd8, 0x39, 0x2e,
	0xc5, 0xa2, 0x12, 0x0a, 0x14, 0x5f, 0xd8, 0x7e, 0xcd, 0xaa, 0xea, 0xac, 0x13, 0xa2, 0x1c, 0xfc,
	0x39, 0x8d, 0x40, 0x16, 0xc1, 0xe6, 0x6b, 0x81, 0xb8, 0xb8, 0x6a, 0x98, 0x68, 0x4c, 0x3d, 0xa3,
	0xdf, 0xcc, 0xc8, 0x33, 0x80, 0x53, 0x51, 0x35, 0x95, 0x0c, 0xdf, 0x9e, 0xcd, 0x77, 0x37, 0xca,
	0xe8, 0x39, 0x1a, 0xd0, 0x33, 0xe8, 0xe9, 0xc9, 0x4f, 0xad, 0x6a, 0x68, 0xcd, 0x35, 0x72, 0xce,
	0x65, 0x8f, 0xe1, 0x93, 0x31, 0x24, 0x47, 0xe7, 0xab, 0xe5, 0xdf, 0x70, 0xf4, 0x92, 0x46, 0xe0,
	0xad, 0x11, 0x03, 0xd5, 0xf7, 0x61, 0x67, 0x26, 0x32, 0x61, 0xaa, 0x77, 0x36, 0x87, 0x1f, 0xd0,
	0x07, 0x03, 0x82, 0x18, 0xb5, 0x25, 0xd5, 0x7a, 0x12, 0xf9, 0xd9, 0xe9, 0x4b, 0x79, 0x95, 0x83,
	0xff, 0xa0, 0x11, 0x43, 0x6a, 0x1b, 0x3d, 0x7d, 0xa2, 0xa7, 0xd4, 0xaf, 0xf8, 0x2c, 0xf2, 0x56,
	0x3f, 0x69, 0x30, 0x0e, 0xdb, 0x89, 0xb8, 0x2c, 0x05, 0x7e, 0xaa, 0x9d, 0xb5, 0x80, 0x04, 0xe3,
	0x0f, 0x94, 0x82, 0x6b, 0xf7, 0x3a, 0xb7, 0x9e, 0xa3, 0x5c, 0x7e, 0xf9, 0x89, 0x1d, 0xc5, 0x95,
	0xbb, 0xf6, 0xac, 0x23, 0xf9, 0xda, 0xc5, 0x0f, 0x68, 0xc4, 0x90, 0x0a, 0xad, 0xa2, 0x4d, 0xf2,
	0x3f, 0x2a, 0x7a, 0x7b, 0xae, 0x0f, 0xb0, 0xfd, 0xaa, 0xb8, 0x4a, 0xf3, 0x26, 0xd5, 0x89, 0xe3,
	0x58, 0xe9, 0xa6, 0x23, 0xab, 0x69, 0xe2, 0x4f, 0xfa, 0x21, 0xfc, 0x3b, 0xc9, 0x8b, 0x46, 0x44,
	0x6f, 0x48, 0x44, 0xbf, 0x2f, 0xa2, 0xb5, 0x16, 0x23, 0xb2, 0x16, 0xd6, 0x4c, 0x01, 0x9d, 0xe9,
	0x29, 0xdc, 0xb1, 0x33, 0xc8, 0xb1, 0xd6, 0x28, 0xc4, 0xcf, 0xba, 0x61, 0xff, 0xd0, 0xf5, 0xd1,
	0xaf, 0x00, 0xc6, 0xb2, 0xd1, 0x77, 0xa2, 0xfc, 0x9a, 0x5e, 0x08, 0xf6, 0x0c, 0xc0, 0x5c, 0x3d,
	0xb6, 0xa7, 0xa9, 0x24, 0xa7, 0x33, 0x76, 0xa1, 0xc8, 0x1e, 0xc2, 0xa6, 0x3e, 0x43, 0x6c, 0x57,
	0x3f, 0x30, 0x47, 0x30, 0xee, 0x41, 0x28, 0x4b, 0x99, 0xe3, 0xd1, 0x96, 0x22, 0x17, 0x28, 0x76,
	0xa1, 0x2a, 0xd2, 0x5c, 0x82, 0x36, 0x92, 0x5c, 0x8f, 0xd8, 0x85, 0x22, 0x7b, 0x01, 0x1d, 0xd1,
	0xf4, 0xab, 0x8e, 0x0e, 0xb1, 0x1b, 0x47, 0x43, 0x8f, 0xfa, 0xdf, 0x46, 0x89, 0xd0, 0xab, 0x19,
	0xbb, 0x50, 0x64, 0x8f, 0x21, 0x54, 0x8b, 0xc6, 0xee, 0x6a, 0xb7, 0xbd, 0xce, 0xb1, 0x03, 0x6c,
	0x18, 0x55, 0x95, 0x2c, 0xfa, 0x9a, 0x90, 0x1e, 0x64, 0x31, 0x4a, 0xba, 0x23, 0x3f, 0xf0, 0xd8,
	0x85, 0x5a, 0x8c, 0x92, 0x48, 0xf2, 0xeb, 0x8d, 0x5d, 0x28, 0x7e, 0xdc, 0x50, 0xe0, 0x93, 0xdf,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x27, 0x7c, 0xbf, 0x84, 0xb9, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	CreateItem(ctx context.Context, in *CreateItemReq, opts ...grpc.CallOption) (*CreateItemRes, error)
	GetItem(ctx context.Context, in *GetItemReq, opts ...grpc.CallOption) (*GetItemRes, error)
	UpdateItem(ctx context.Context, in *UpdateItemReq, opts ...grpc.CallOption) (*UpdateItemRes, error)
	DeleteItem(ctx context.Context, in *DeleteItemReq, opts ...grpc.CallOption) (*DeleteItemRes, error)
	RefreshToken(ctx context.Context, in *RefreshTokenReq, opts ...grpc.CallOption) (*RefreshTokenRes, error)
	CreateUser(ctx context.Context, in *CreateUserReq, opts ...grpc.CallOption) (*CreateUserRes, error)
	Login(ctx context.Context, in *LoginUserReq, opts ...grpc.CallOption) (*LoginUserRes, error)
	GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*GetUserRes, error)
	UpdateUser(ctx context.Context, in *UpdateUserReq, opts ...grpc.CallOption) (*UpdateUserRes, error)
	DeleteUser(ctx context.Context, in *DeleteUserReq, opts ...grpc.CallOption) (*DeleteUserRes, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) CreateItem(ctx context.Context, in *CreateItemReq, opts ...grpc.CallOption) (*CreateItemRes, error) {
	out := new(CreateItemRes)
	err := c.cc.Invoke(ctx, "/proto.UserService/CreateItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetItem(ctx context.Context, in *GetItemReq, opts ...grpc.CallOption) (*GetItemRes, error) {
	out := new(GetItemRes)
	err := c.cc.Invoke(ctx, "/proto.UserService/GetItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateItem(ctx context.Context, in *UpdateItemReq, opts ...grpc.CallOption) (*UpdateItemRes, error) {
	out := new(UpdateItemRes)
	err := c.cc.Invoke(ctx, "/proto.UserService/UpdateItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteItem(ctx context.Context, in *DeleteItemReq, opts ...grpc.CallOption) (*DeleteItemRes, error) {
	out := new(DeleteItemRes)
	err := c.cc.Invoke(ctx, "/proto.UserService/DeleteItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) RefreshToken(ctx context.Context, in *RefreshTokenReq, opts ...grpc.CallOption) (*RefreshTokenRes, error) {
	out := new(RefreshTokenRes)
	err := c.cc.Invoke(ctx, "/proto.UserService/RefreshToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CreateUser(ctx context.Context, in *CreateUserReq, opts ...grpc.CallOption) (*CreateUserRes, error) {
	out := new(CreateUserRes)
	err := c.cc.Invoke(ctx, "/proto.UserService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Login(ctx context.Context, in *LoginUserReq, opts ...grpc.CallOption) (*LoginUserRes, error) {
	out := new(LoginUserRes)
	err := c.cc.Invoke(ctx, "/proto.UserService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUser(ctx context.Context, in *GetUserReq, opts ...grpc.CallOption) (*GetUserRes, error) {
	out := new(GetUserRes)
	err := c.cc.Invoke(ctx, "/proto.UserService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUser(ctx context.Context, in *UpdateUserReq, opts ...grpc.CallOption) (*UpdateUserRes, error) {
	out := new(UpdateUserRes)
	err := c.cc.Invoke(ctx, "/proto.UserService/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DeleteUser(ctx context.Context, in *DeleteUserReq, opts ...grpc.CallOption) (*DeleteUserRes, error) {
	out := new(DeleteUserRes)
	err := c.cc.Invoke(ctx, "/proto.UserService/DeleteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	CreateItem(context.Context, *CreateItemReq) (*CreateItemRes, error)
	GetItem(context.Context, *GetItemReq) (*GetItemRes, error)
	UpdateItem(context.Context, *UpdateItemReq) (*UpdateItemRes, error)
	DeleteItem(context.Context, *DeleteItemReq) (*DeleteItemRes, error)
	RefreshToken(context.Context, *RefreshTokenReq) (*RefreshTokenRes, error)
	CreateUser(context.Context, *CreateUserReq) (*CreateUserRes, error)
	Login(context.Context, *LoginUserReq) (*LoginUserRes, error)
	GetUser(context.Context, *GetUserReq) (*GetUserRes, error)
	UpdateUser(context.Context, *UpdateUserReq) (*UpdateUserRes, error)
	DeleteUser(context.Context, *DeleteUserReq) (*DeleteUserRes, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) CreateItem(ctx context.Context, req *CreateItemReq) (*CreateItemRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateItem not implemented")
}
func (*UnimplementedUserServiceServer) GetItem(ctx context.Context, req *GetItemReq) (*GetItemRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetItem not implemented")
}
func (*UnimplementedUserServiceServer) UpdateItem(ctx context.Context, req *UpdateItemReq) (*UpdateItemRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateItem not implemented")
}
func (*UnimplementedUserServiceServer) DeleteItem(ctx context.Context, req *DeleteItemReq) (*DeleteItemRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteItem not implemented")
}
func (*UnimplementedUserServiceServer) RefreshToken(ctx context.Context, req *RefreshTokenReq) (*RefreshTokenRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshToken not implemented")
}
func (*UnimplementedUserServiceServer) CreateUser(ctx context.Context, req *CreateUserReq) (*CreateUserRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (*UnimplementedUserServiceServer) Login(ctx context.Context, req *LoginUserReq) (*LoginUserRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedUserServiceServer) GetUser(ctx context.Context, req *GetUserReq) (*GetUserRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (*UnimplementedUserServiceServer) UpdateUser(ctx context.Context, req *UpdateUserReq) (*UpdateUserRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (*UnimplementedUserServiceServer) DeleteUser(ctx context.Context, req *DeleteUserReq) (*DeleteUserRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUser not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_CreateItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateItemReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/CreateItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateItem(ctx, req.(*CreateItemReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetItemReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/GetItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetItem(ctx, req.(*GetItemReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateItemReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/UpdateItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateItem(ctx, req.(*UpdateItemReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteItemReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/DeleteItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteItem(ctx, req.(*DeleteItemReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_RefreshToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).RefreshToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/RefreshToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).RefreshToken(ctx, req.(*RefreshTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUser(ctx, req.(*CreateUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Login(ctx, req.(*LoginUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUser(ctx, req.(*GetUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateUser(ctx, req.(*UpdateUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.UserService/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DeleteUser(ctx, req.(*DeleteUserReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateItem",
			Handler:    _UserService_CreateItem_Handler,
		},
		{
			MethodName: "GetItem",
			Handler:    _UserService_GetItem_Handler,
		},
		{
			MethodName: "UpdateItem",
			Handler:    _UserService_UpdateItem_Handler,
		},
		{
			MethodName: "DeleteItem",
			Handler:    _UserService_DeleteItem_Handler,
		},
		{
			MethodName: "RefreshToken",
			Handler:    _UserService_RefreshToken_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _UserService_CreateUser_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _UserService_Login_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _UserService_GetUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _UserService_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _UserService_DeleteUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
